const COEFFICIENT = 100;

const GOLDEN_RATIO = 1.618;
const SILVER_RATIO = 1.414;
const PLATINUM_RATIO = 1.732;

export const AspectRatio = {
  R_4_BY_3: (3 / 4) * COEFFICIENT,
  R_3_BY_4: (4 / 3) * COEFFICIENT,
  R_16_BY_9: (9 / 16) * COEFFICIENT,
  R_1_BY_1: COEFFICIENT,
  GOLDEN_VERTICAL: GOLDEN_RATIO * COEFFICIENT,
  GOLDEN_HORIZONTAL: (1 / GOLDEN_RATIO) * COEFFICIENT,
  SILVER_VERTICAL: SILVER_RATIO * COEFFICIENT,
  SILVER_HORIZONTAL: (1 / SILVER_RATIO) * COEFFICIENT,
  PLATINUM_VERTICAL: PLATINUM_RATIO * COEFFICIENT,
  PLATINUM_HORIZONTAL: (1 / PLATINUM_RATIO) * COEFFICIENT,
} as const;
